/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'
import { Route as CaseCaseIdIndexRouteImport } from './routes/case.$caseId.index'
import { Route as CaseCaseIdTimelineRouteImport } from './routes/case.$caseId.timeline'
import { Route as CaseCaseIdCorrelationRouteImport } from './routes/case.$caseId.correlation'
import { Route as CaseCaseIdAutopsyRouteImport } from './routes/case.$caseId.autopsy'

const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdIndexRoute = CaseCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdTimelineRoute = CaseCaseIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdCorrelationRoute = CaseCaseIdCorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdAutopsyRoute = CaseCaseIdAutopsyRouteImport.update({
  id: '/autopsy',
  path: '/autopsy',
  getParentRoute: () => CaseCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/autopsy': typeof CaseCaseIdAutopsyRoute
  '/case/$caseId/correlation': typeof CaseCaseIdCorrelationRoute
  '/case/$caseId/timeline': typeof CaseCaseIdTimelineRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/case/$caseId/autopsy': typeof CaseCaseIdAutopsyRoute
  '/case/$caseId/correlation': typeof CaseCaseIdCorrelationRoute
  '/case/$caseId/timeline': typeof CaseCaseIdTimelineRoute
  '/case/$caseId': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/autopsy': typeof CaseCaseIdAutopsyRoute
  '/case/$caseId/correlation': typeof CaseCaseIdCorrelationRoute
  '/case/$caseId/timeline': typeof CaseCaseIdTimelineRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/case/$caseId'
    | '/case/$caseId/autopsy'
    | '/case/$caseId/correlation'
    | '/case/$caseId/timeline'
    | '/case/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/case/$caseId/autopsy'
    | '/case/$caseId/correlation'
    | '/case/$caseId/timeline'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/case/$caseId'
    | '/case/$caseId/autopsy'
    | '/case/$caseId/correlation'
    | '/case/$caseId/timeline'
    | '/case/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  CaseCaseIdRoute: typeof CaseCaseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/': {
      id: '/case/$caseId/'
      path: '/'
      fullPath: '/case/$caseId/'
      preLoaderRoute: typeof CaseCaseIdIndexRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/timeline': {
      id: '/case/$caseId/timeline'
      path: '/timeline'
      fullPath: '/case/$caseId/timeline'
      preLoaderRoute: typeof CaseCaseIdTimelineRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/correlation': {
      id: '/case/$caseId/correlation'
      path: '/correlation'
      fullPath: '/case/$caseId/correlation'
      preLoaderRoute: typeof CaseCaseIdCorrelationRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/autopsy': {
      id: '/case/$caseId/autopsy'
      path: '/autopsy'
      fullPath: '/case/$caseId/autopsy'
      preLoaderRoute: typeof CaseCaseIdAutopsyRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
  }
}

interface CaseCaseIdRouteChildren {
  CaseCaseIdAutopsyRoute: typeof CaseCaseIdAutopsyRoute
  CaseCaseIdCorrelationRoute: typeof CaseCaseIdCorrelationRoute
  CaseCaseIdTimelineRoute: typeof CaseCaseIdTimelineRoute
  CaseCaseIdIndexRoute: typeof CaseCaseIdIndexRoute
}

const CaseCaseIdRouteChildren: CaseCaseIdRouteChildren = {
  CaseCaseIdAutopsyRoute: CaseCaseIdAutopsyRoute,
  CaseCaseIdCorrelationRoute: CaseCaseIdCorrelationRoute,
  CaseCaseIdTimelineRoute: CaseCaseIdTimelineRoute,
  CaseCaseIdIndexRoute: CaseCaseIdIndexRoute,
}

const CaseCaseIdRouteWithChildren = CaseCaseIdRoute._addFileChildren(
  CaseCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  CaseCaseIdRoute: CaseCaseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
